### ISSUE TITLE
样式更改记录

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/hackernews-react#9]
样式更改记录
1. menu居中
2. 更改logo图品的大小
3. 修改profile中span样式
4. 将部分样式比如spinner /header 单独抽出来变成一个scss文件

**Comment by ckinmind** [comment]
1. menu居中
```css
.menu {
  height: 40px;
  width: 960px;
  margin: 0 auto;
  text-align: left;
  position: relative;
  top: 115px;
}
```
>将text-align改为center
